import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore,collection,getDocs,addDoc,doc,updateDoc,deleteDoc,setDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);let cars=[],contact={wa:"6281234567890",tg:"#",tt:"#",yt:"#"},editingId=null;
const defaults=[{id:"default-r35",name:"Nissan GT-R R35",price:35000,type:"sport",image:"",status:"available",active:true},{id:"default-supra",name:"Toyota Supra MK4",price:30000,type:"jdm",image:"",status:"available",active:true},{id:"default-m4",name:"BMW M4",price:40000,type:"luxury",image:"",status:"available",active:true},{id:"default-huracan",name:"Lamborghini Huracan",price:50000,type:"sport",image:"",status:"available",active:true},{id:"default-s15",name:"Nissan Silvia S15",price:28000,type:"jdm",image:"",status:"available",active:true},{id:"default-amg",name:"Mercedes AMG GT",price:45000,type:"luxury",image:"",status:"available",active:true}];
const money=n=>"Rp "+Number(n||0).toLocaleString("id-ID");
onAuthStateChanged(auth,async u=>{if(u){loginScreen.classList.add("hidden");adminApp.classList.remove("hidden");await loadAll();renderAdmin()}else{loginScreen.classList.remove("hidden");adminApp.classList.add("hidden")}});
window.adminLogin=async()=>{try{await signInWithEmailAndPassword(auth,loginUser.value.trim(),loginPass.value)}catch(e){alert("Login gagal. Pastikan Email/Password Firebase benar.")}};window.adminLogout=()=>signOut(auth);
document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>showAdminPage(b.dataset.ap));
window.showAdminPage=id=>{document.querySelectorAll(".admin-page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".navbtn").forEach(x=>x.classList.toggle("active",x.dataset.ap===id));adminTitle.textContent={dash:"Dashboard",manage:"Kelola Mobil",orders:"Pesanan",contact:"CS Admin & Social Media",settings:"Pengaturan Toko"}[id];renderAdmin()};
async function loadAll(){const ps=await getDocs(collection(db,"products"));cars=ps.docs.map(d=>({id:d.id,...d.data()}));if(!cars.length){for(const c of defaults)await setDoc(doc(db,"products",c.id),c);cars=defaults.map(x=>({...x}))}const ss=await getDocs(collection(db,"settings"));const pub=ss.docs.find(d=>d.id==="public");if(pub)contact={...contact,...pub.data()};applyContact()}
function renderAdmin(){aTotal.textContent=cars.length;aAvailable.textContent=cars.filter(c=>c.status==="available"&&c.active!==false).length;if(manage.classList.contains("active"))renderAdminCars()}
window.renderAdminCars=()=>{const q=(adminSearch.value||"").toLowerCase();adminCars.innerHTML=cars.filter(c=>String(c.name||"").toLowerCase().includes(q)).map(c=>`<div class="car-row"><div class="thumb" ${c.image?`style="background-image:url('${String(c.image).replace(/'/g,"\\'")}');background-size:cover;background-position:center;color:transparent"`:""}>${c.image?"":"CAR"}</div><div><h3>${c.name}</h3><p>${money(c.price)} • ${String(c.type||"").toUpperCase()} • ${c.status==="available"?"TERSEDIA":"HABIS"} • ${c.active!==false?"AKTIF":"NONAKTIF"}</p></div><div class="row"><button onclick="editCar('${c.id}')">Edit</button><button onclick="deleteCar('${c.id}')">Hapus</button></div></div>`).join("")||"<div class='admin-panel' style='text-align:center;color:#617b92'>Mobil tidak ditemukan.</div>"};
window.openCarForm=()=>{editingId=null;modalTitle.textContent="Tambah Mobil";carName.value="";carPrice.value="";carImage.value="";carType.value="sport";carStatus.value="available";carModal.classList.remove("hidden")};window.editCar=id=>{const c=cars.find(x=>x.id===id);if(!c)return;editingId=id;modalTitle.textContent="Edit Mobil";carName.value=c.name||"";carPrice.value=c.price||0;carType.value=c.type||"sport";carImage.value=c.image||"";carStatus.value=c.status||"available";carModal.classList.remove("hidden")};window.closeCarForm=()=>carModal.classList.add("hidden");
window.saveCar=async()=>{const data={name:carName.value.trim(),price:Number(carPrice.value),type:carType.value,image:carImage.value.trim(),status:carStatus.value,active:true};if(!data.name||!data.price)return alert("Nama dan harga wajib diisi.");if(editingId)await updateDoc(doc(db,"products",editingId),data);else await addDoc(collection(db,"products"),data);await loadAll();closeCarForm();renderAdmin()};window.deleteCar=async id=>{if(confirm("Hapus mobil ini?")){await deleteDoc(doc(db,"products",id));await loadAll();renderAdmin()}};
window.saveContact=async()=>{contact={wa:editWa.value.trim(),tg:editTg.value.trim(),tt:editTt.value.trim(),yt:editYt.value.trim()};await setDoc(doc(db,"settings","public"),contact,{merge:true});applyContact();alert("CS & Social berhasil disimpan.")};function applyContact(){editWa.value=contact.wa||"";editTg.value=contact.tg||"";editTt.value=contact.tt||"";editYt.value=contact.yt||""}window.saveSettings=()=>alert("Pengaturan dasar ini mengikuti branding Store.");
window.addEventListener("DOMContentLoaded",()=>adminSearch?.addEventListener("input",renderAdminCars));
