import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore,collection,getDocs,addDoc,doc,updateDoc,deleteDoc,query,orderBy } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js";

const appFb=initializeApp(firebaseConfig),db=getFirestore(appFb),auth=getAuth(appFb);
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
loginForm.onsubmit=async e=>{e.preventDefault();loginError.textContent="";try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(err){loginError.textContent="Login gagal."}};
logout.onclick=()=>signOut(auth);
document.querySelectorAll("aside button[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));
onAuthStateChanged(auth,user=>{if(user){login.classList.add("hidden");app.classList.remove("hidden");page("dashboard")}else{login.classList.remove("hidden");app.classList.add("hidden")}});
async function getProducts(){return (await getDocs(collection(db,"products"))).docs.map(d=>({id:d.id,...d.data()}))}
async function getOrders(){return (await getDocs(query(collection(db,"orders"),orderBy("createdAt","desc")))).docs.map(d=>({id:d.id,...d.data()}))}
async function page(p){if(p==="dashboard")await dashboard();if(p==="products")await products();if(p==="orders")await orders()}
async function dashboard(){const [ps,os]=await Promise.all([getProducts(),getOrders()]);content.innerHTML=`<h1>Dashboard</h1><div class="cards"><div class="stat">Produk<br><b>${ps.length}</b></div><div class="stat">Pesanan<br><b>${os.length}</b></div><div class="stat">Pendapatan<br><b>${rupiah(os.reduce((s,o)=>s+(o.total||0),0))}</b></div></div>`}
async function products(){const ps=await getProducts();content.innerHTML=`<h1>Produk</h1><div class="toolbar"><button class="primary" id="add">+ Tambah produk</button></div><div class="table"><table><tr><th>Foto</th><th>Nama</th><th>Harga</th><th>Stok</th><th>Aktif</th><th>Aksi</th></tr>${ps.map(p=>`<tr><td><img class="mini" src="${p.image||"https://placehold.co/100"}"></td><td>${p.name}</td><td>${rupiah(p.price||0)}</td><td>${p.stock??0}</td><td>${p.active?"Ya":"Tidak"}</td><td><button class="edit" onclick="editProduct('${p.id}')">Edit</button> <button class="danger" onclick="deleteProduct('${p.id}')">Hapus</button></td></tr>`).join("")}</table></div>`;add.onclick=()=>productForm()}
function productForm(p=null){content.innerHTML=`<h1>${p?"Edit":"Tambah"} Produk</h1><form class="form" id="pf"><input id="pn" required placeholder="Nama" value="${p?.name||""}"><input id="pp" required type="number" placeholder="Harga" value="${p?.price||""}"><input id="ps" required type="number" placeholder="Stok" value="${p?.stock||0}"><input id="pi" required placeholder="URL gambar" value="${p?.image||""}"><label><input id="pa" type="checkbox" ${p?.active!==false?"checked":""}> Produk aktif</label><button class="primary">Simpan</button></form>`;pf.onsubmit=async e=>{e.preventDefault();const data={name:pn.value,price:Number(pp.value),stock:Number(ps.value),image:pi.value,active:pa.checked,createdAt:p?.createdAt||new Date().toISOString()};try{if(p)await updateDoc(doc(db,"products",p.id),data);else await addDoc(collection(db,"products"),data);await products()}catch(err){alert("Gagal menyimpan. Cek Firestore Rules.")}}}
window.editProduct=async id=>{const p=(await getProducts()).find(x=>x.id===id);productForm(p)}
window.deleteProduct=async id=>{if(confirm("Hapus produk?")){await deleteDoc(doc(db,"products",id));products()}}
async function orders(){const os=await getOrders();content.innerHTML=`<h1>Pesanan</h1><div class="table"><table><tr><th>ID</th><th>Customer</th><th>WhatsApp</th><th>Alamat</th><th>Total</th><th>Status</th><th>Aksi</th></tr>${os.map(o=>`<tr><td>${o.id.slice(0,8)}</td><td>${o.customerName}</td><td>${o.phone}</td><td>${o.address}</td><td>${rupiah(o.total||0)}</td><td>${o.status}</td><td><button class="edit" onclick="changeStatus('${o.id}')">Ubah</button></td></tr>`).join("")||"<tr><td colspan=7>Belum ada pesanan.</td></tr>"}</table></div>`}
window.changeStatus=async id=>{const s=prompt("Status: Baru / Diproses / Dikirim / Selesai / Batal");if(!s)return;await updateDoc(doc(db,"orders",id),{status:s});orders()}
